name: POC
run-name: POC
on: 
    - push
    - workflow_dispatch

env:
  SPECTRAL_DSN: ${{ secrets.SPECTRAL_DSN }}

jobs: 
    dependencies:
      name: 'Install NPM deps'
      runs-on: ubuntu-22.04
      steps:
        - name: 'Checkout'
          uses: actions/checkout@v3
        - name: 'Setup Node16'
          uses: actions/setup-node@v3
          with:
            node-version: '16'
        - name: 'Install deps'
          run: npm ci
        - name: 'Update cache if package-lock change'
          uses: actions/cache/save@v3
          id: npm_modules
          with:
            path: './node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}


    scan:
      runs-on: ubuntu-22.04
      steps:
      - uses: actions/checkout@v3
      - name: Install and run Spectral CI
        uses: spectralops/spectral-github-action@v2
        with:
          spectral-dsn: ${{ env.SPECTRAL_DSN }}
          spectral-args: scan --ok --engines secrets,iac,oss --include-tags base,iac,audit
      


      
            