name: POC
run-name: POC
on: 
    - push
    - workflow_dispatch
jobs: 
    dependencies:
      name: 'Install NPM deps'
      runs-on: ubuntu-22.04
      steps:
        - name: 'Checkout'
          uses: actions/checkout@v3
        - name: 'Setup Node16'
          uses: actions/setup-node@v3
          with:
            node-version: '16'
        - name: 'Install deps'
          run: npm ci
        - name: 'Update cache if package-lock change'
          uses: actions/cache/save@v3
          id: npm_modules
          with:
            path: './node_modules'
            key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

    
    osv-scanner:
        name: "OSV-SCANNER"
        runs-on: ubuntu-22.04
        steps:
            - name: 'checkout'
              uses: actions/checkout@v3
            - uses: actions/setup-go@v4
              with:
                go-version: '1.19'
            - name: 'install scanner'
              run: "go install github.com/google/osv-scanner/cmd/osv-scanner@v1"
            - name: "scan"
              run: "osv-scanner --lockfile=package-lock.json"
              
              
            